version: '3.8'

services:
  json-reports-app:
    build: .
    container_name: json-reports-tools
    ports:
      - "8504:8504"
    environment:
      - STREAMLIT_SERVER_PORT=8504
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      # Optional: Mount config directory for easy updates
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8504/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 