# Wei TR-181 Validation Rules
# Broadband Forum TR-181 Device Data Model validation rules

name: "Wei TR-181 Metrics"
description: "Validation rules for TR-181 device data model metrics"
version: "1.0"

rules:
  - name: "TR-181 Baseline TP-Link"
    description: "Baseline metrics required for wei v1"
    category: "Bulkdata"
    patterns:
      - "Device.DeviceInfo.UpTime"
      - "Device.DeviceInfo.SerialNumber"
      - "Device.DeviceInfo.Manufacturer"
      - "Device.DeviceInfo.ManufacturerOUI"
      - "Device.DeviceInfo.ModelName"
      - "Device.DeviceInfo.Description"
      - "Device.DeviceInfo.ProductClass"
      - "Device.DeviceInfo.HardwareVersion"
      - "Device.DeviceInfo.SoftwareVersion"
      - "Device.DeviceInfo.MemoryStatus.Free"
      - "Device.DeviceInfo.MemoryStatus.Total"
      - "Device.DeviceInfo.ProcessStatus.CPUUsage"
      - "Device.ManagementServer.ConnectionRequestURL"
      - "Device.Firewall.Enable"
      - "Device.WiFi.Radio.*.Enable"
      - "Device.WiFi.Radio.*.Channel"
      - "Device.WiFi.Radio.*.Status"
      - "Device.WiFi.Radio.*.CurrentOperatingChannelBandwidth"
      - "Device.WiFi.Radio.*.OperatingFrequencyBand"
      - "Device.WiFi.Radio.*.OperatingChannelBandwidth"
      - "Device.WiFi.Radio.*.OperatingStandards"
      - "Device.WiFi.Radio.*.SupportedStandards"
      - "Device.WiFi.Radio.*.AutoChannelEnable"
      - "Device.WiFi.Radio.*.AutoChannelSupported"
      - "Device.WiFi.Radio.*.TransmitPower"
      - "Device.WiFi.Radio.*.Stats.Noise"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.Noise"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.Utilization"
      - "Device.WiFi.Radio.*.Stats.BytesSent"
      - "Device.WiFi.Radio.*.Stats.BytesReceived"
      - "Device.WiFi.Radio.*.Stats.PacketsSent"
      - "Device.WiFi.Radio.*.Stats.PacketsReceived"
      - "Device.WiFi.Radio.*.Stats.ErrorsSent"
      - "Device.WiFi.Radio.*.Stats.ErrorsReceived"
      - "Device.WiFi.Radio.*.Stats.DiscardPacketsSent"
      - "Device.WiFi.Radio.*.Stats.DiscardPacketsReceived"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.BSS.*.SSID"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.BSS.*.STA.*.MACAddress"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.BSS.*.STA.*.BytesSent"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.BSS.*.STA.*.BytesReceived"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.BSS.*.STA.*.LastConnectTime"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.BSS.*.STA.*.LastDataDownlinkRate"
      - "Device.WiFi.DataElements.Network.Device.*.Radio.*.BSS.*.STA.*.LastDataUplinkRate"
      - "Device.WiFi.SSID.*.SSID"
      - "Device.WiFi.SSID.*.LowerLayers"
      - "Device.WiFi.AccessPoint.*.Enable"
      - "Device.WiFi.AccessPoint.*.Status"
      - "Device.WiFi.AccessPoint.*.SSIDReference"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.MACAddress"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.SignalStrength"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.OperatingStandard"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.LastDataUplinkRate"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.LastDataDownlinkRate"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.BytesSent"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.ErrorsSent"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.RetryCount"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.PacketsSent"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.RetransCount"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.BytesReceived"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.ErrorsReceived"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.PacketsReceived"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.FailedRetransCount"
      - "Device.WiFi.AccessPoint.*.AssociatedDevice.*.Stats.MultipleRetryCount"
      - "Device.WiFi.X_TP_BandSteering.Enable"
      - "Device.Hosts.Host.*.Active"
      - "Device.Hosts.Host.*.ClientID"
      - "Device.Hosts.Host.*.HostName"
      - "Device.Hosts.Host.*.IPAddress"
      - "Device.Hosts.Host.*.PhysAddress"
      - "Device.Hosts.Host.*.InterfaceType"
      - "Device.WiFi.Radio.*.ChannelsInUse"